apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ngx
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
          - name: myapp
            hostPath:
              path: /tmp/ngx-log
              type: Directory
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: myapp
            mountPath: /var/log/nginx
        
